crabapples.AES_KEY: crabapples
crabapples.REDIS_PREFIX: crabapples
crabapples.TOKEN_CACHE_TIME: 30
crabapples.SALT: crabapples
dataBaseParam: useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true
#上传文件配置
virtualPath: /file/
###
server.port: 9093
server.application.name: learn

spring.profiles.active: dev
spring.servlet.multipart.max-file-size: 100MB

#mybatis.mapper-locations: classpath*:mapper/*.xml,classpath*:cn/crabapples/**/dao/mybatis/xml/*.xml
#mybatis-plus.mapper-locations: classpath*:mapper/*.xml,classpath*:cn/crabapples/**/dao/mybatis/xml/*.xml
mybatis-flex.mapper-locations: classpath*:mapper/*.xml,classpath*:cn/crabapples/**/dao/mybatis/xml/*.xml
# nacos配置
nacos.config.server-addr: 192.168.3.20:8848
# 日志配置
logging.file.name: logs/springboot-jwt/
# 邮件配置
mail:
  host: smtp.qq.com
  username: xxxxx@qq.com
  password: xxxxx
  source: xxxxx@qq.com
  port: 465
  isAuth: true
  isDebug: true

