isDebug: true
dadaBaseUrl: 'localhost'
dataBaseDriveV8: 'com.mysql.cj.jdbc.Driver'
dataBaseDriveV5: 'com.mysql.jdbc.Driver'
dataBaseParam: 'useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true'
virtualPath: '/file/'
filePath: '/home/mrhe/uploadPath/'
mail:
  host: 'smtp.qq.com'
  username: 'xxxxx@qq.com'
  password: 'xxxxx'
  source: 'xxxxx@qq.com'
  port: '465'
  isAuth: true
  isDebug: true
logging:
  pattern:
    level: info
spring:
  data:
    mongodb:
      database: learn
      host: 127.0.0.1
  jpa:
    show-sql: false #是否在控制台显示数据库语句
    hibernate:
      ddl-auto: update #每次启动时如何操作对应表
    database-platform: org.hibernate.dialect.MySQL8Dialect #设置jpa方言为mysql
  rabbitmq:
    host: 192.168.3.20
    port: 5672
    username: crabapples
    password: crabapples
    virtual-host: /crabapples
  redis:
    host: localhost
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 10
  datasource:
    driverClassName: ${dataBaseDriveV8} #数据库驱动
    url: jdbc:mysql://${dadaBaseUrl}:3306/learn?useSSL=false&${dataBaseParam} #数据库地址
    username: root #数据库用户名
    password: root #数据库密码
  #    dbcp2:
  #      driver-class-name: ${dataBaseDriveV8}
  #      url: jdbc:mysql://${dadaBaseUrl}:3306/learn?useSSL=false&${dataBaseParam} #数据库地址
  #      username: learn #数据库用户名
  #      password: learn #数据库密码
  ##      max-conn-lifetime-millis: 10
  ##      validation-query-timeout: 1
  #      initial-size: 20
  #      max-idle: 50
  #      min-idle: 20
  #      max-wait-millis: 10
  #      max-total: 90
  #      remove-abandoned-timeout: 2
  #      test-on-borrow: true
  #      validation-query: SELECT 1


  #    type: com.alibaba.druid.pool.DruidDataSource
  #    driverClassName: com.mysql.jdbc.Driver



